---
dist: trusty
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  matrix:
    - MOLECULE_DISTRO: centos/systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: debian:jessie
    - MOLECULE_DISTRO: debian:stretch

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
