{% set distribution = item.image.split(':', 1)[0] %}
{% set version = item.image.split(':', 1)[1] %}
{% set docker_dir = '{}-{}'.format(distribution, version %}
{{ lookup('url', 'https://raw.githubusercontent.com/ericsysmin/docker-ansible-testing/master/' ~ docker_dir ~ '/Dockerfile') }}"
