{% set docker_dir = '{}-{}'.format(item.image.split(':', 1)[0], item.image.split(':', 1)[1]) %}
{{ lookup('url', 'https://raw.githubusercontent.com/ericsysmin/docker-ansible-testing/master/' ~ item.image ~ '/Dockerfile', split_lines=False) }}
